steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "--build-arg"
      - "NEXT_PUBLIC_SITE_URL=https://politicamoderna.info"
      - "--build-arg"
      - "NEXT_PUBLIC_SITE_NAME=Politica Moderna"
      - "--build-arg"
      - "NEXT_PUBLIC_SANITY_PROJECT_ID=33umjun9"
      - "--build-arg"
      - "NEXT_PUBLIC_SANITY_DATASET=production"
      - "--build-arg"
      - "NEXT_PUBLIC_SANITY_API_VERSION=2025-02-19"
      - "--build-arg"
      - "REVALIDATE_SECRET=replace-this-with-a-random-secret"
      - "-t"
      - "us-central1-docker.pkg.dev/politicamoderna-prod/politicamoderna/politicamoderna-web:$COMMIT_SHA"
      - "-t"
      - "us-central1-docker.pkg.dev/politicamoderna-prod/politicamoderna/politicamoderna-web:latest"
      - "."

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "--all-tags"
      - "us-central1-docker.pkg.dev/politicamoderna-prod/politicamoderna/politicamoderna-web"

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "politicamoderna-web"
      - "--image"
      - "us-central1-docker.pkg.dev/politicamoderna-prod/politicamoderna/politicamoderna-web:$COMMIT_SHA"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"

images:
  - "us-central1-docker.pkg.dev/politicamoderna-prod/politicamoderna/politicamoderna-web:$COMMIT_SHA"
  - "us-central1-docker.pkg.dev/politicamoderna-prod/politicamoderna/politicamoderna-web:latest"

options:
  machineType: "E2_HIGHCPU_8"
  logging: CLOUD_LOGGING_ONLY
